name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build package
      run: |
        pip install build
        python3 -m build
    - name: Try wheel
      run: |
        pip install --find-links dist chopro-epub
        pushd tests
        chopro-epub list.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: "dist/*"
